name: Make pdf
on: push
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out markdown
        uses: actions/checkout@v2
      - name: Convert to pdf
        uses: docker://pandoc/latex:2.14.2
        with:
          args: >- 
            --output=gtf.pdf
             ${{ github.workspace }}/README.md
