name: Make pdf
on: push
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: pandoc/latex:2.14.2
        with:
          args: >- 
            --output=gtf.pdf
            README.md
